import {
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaMailBulk,
  FaPhone,
  FaTelegram,
  FaTwitch,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";

export const socialMediaLinks = [
  {
    id: "telegram",
    name: "Telegram",
    icon: FaTelegram,
    url: "https://t.me/realbattlechannel",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: FaWhatsapp,
    url: "https://wa.me/919876543210",
    color: "text-green-400",
    bgColor: "bg-green-500/10 hover:bg-green-500/20",
  },
  {
    id: "discord",
    name: "Discord",
    icon: FaDiscord,
    url: "https://discord.gg/realbattle",
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10 hover:bg-indigo-500/20",
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: FaFacebook,
    url: "https://facebook.com/realbattle",
    color: "text-blue-600",
    bgColor: "bg-blue-600/10 hover:bg-blue-600/20",
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: FaInstagram,
    url: "https://instagram.com/realbattle",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10 hover:bg-pink-500/20",
  },
  {
    id: "youtube",
    name: "YouTube",
    icon: FaYoutube,
    url: "https://youtube.com/@realbattle",
    color: "text-red-500",
    bgColor: "bg-red-500/10 hover:bg-red-500/20",
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: FaTwitch,
    url: "https://twitch.tv/realbattle",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10 hover:bg-purple-500/20",
  },
  {
    id: "github",
    name: "GitHub",
    icon: FaGithub,
    url: "https://github.com/realbattle",
    color: "text-gray-600 dark:text-gray-400",
    bgColor: "bg-gray-600/10 dark:bg-gray-400/10 hover:bg-gray-600/20",
  },
  {
    id: "email",
    name: "Email",
    icon: FaMailBulk,
    url: "mailto:support@realbattle.com",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
  },
  {
    id: "phone",
    name: "Phone",
    icon: FaPhone,
    url: "tel:+919876543210",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10 hover:bg-cyan-500/20",
  },
];
