export const howWeUseSection = {
  id: "how-we-use",
  title: "6. How We Use Your Information",
  type: "list" as const,
  items: [
    "Create and manage your Real Battle account.",
    "Authenticate users and maintain secure login sessions.",
    "Create and manage gaming profiles.",
    "Register users and teams for tournaments.",
    "Operate, schedule, and manage tournament matches.",
    "Calculate scores, rankings, kills, points, and tournament results.",
    "Display tournament leaderboards and historical results.",
    "Verify tournament participation and submitted match proof.",
    "Investigate disputes, complaints, and tournament-related reports.",
    "Detect cheating, fraud, abuse, suspicious activity, and manipulation.",
    "Prevent unauthorized access and protect the security of our services.",
    "Process payments, refunds, prizes, and withdrawals where applicable.",
    "Provide customer support and respond to user requests.",
    "Send important account, security, tournament, and service notifications.",
    "Analyze service usage and improve the performance and functionality of Real Battle.",
    "Maintain technical logs, audit records, and operational records.",
    "Comply with applicable laws, legal obligations, and lawful requests from authorities.",
  ],
};
